### ISSUE TITLE
[Bug] Dynamic Filter edits Google Sheets Cell Contents

### ISSUE THREAD

**Issue by Obsidianninja11** [darkreader/darkreader#10922]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

When editing a cell in google sheets with the dynamic filter on, the text color is reset to black (or white if light mode is enabled).
This does not happen in the other filters (Filter, Filter+, Static).

Why this is a problem:
Dynamic filter provides the best dark mode for google sheets, but editing a cell that utilizes colored text is a hassle with the dynamic filter on (you'd have to manually change the text color back to what it was before you edited it).

### Website Address

https://docs.google.com/spreadsheets

### Steps To Reproduce

(See screenshots for additional info)

1. Turn dark reader and the dynamic filter on.
2. Edit a cell with colored text.
3. Press enter to confirm editing the cell.

4. Additional info: The bug does not appear if you finish editing the cell with dark reader toggled off.

### Expected Behavior

Editing a cell with the dynamic filter on shouldn't change cell contents, and the cell should remain the same color after editing it with the filter enabled.

### Actual Behavior

Editing a cell with the dynamic filter on changes the cell's text color to black.

### Screenshots

1. A red colored cell with dynamic filter on: 
![image](https://user-images.githubusercontent.com/108832807/225727364-9a031f49-273d-4411-bf5d-0d2db519da48.png)
The same cell with dark reader toggled off:
![image](https://user-images.githubusercontent.com/108832807/225727393-b746c368-d54f-4beb-a393-20731518f3e7.png)

2. The red colored cell after starting to edit it (with filter on):
![image](https://user-images.githubusercontent.com/108832807/225727422-cb4aa473-eea4-4ebb-834f-b2de07054102.png)
The same cell with dark reader toggled off:
![image](https://user-images.githubusercontent.com/108832807/225727435-0d8a4a91-0273-4153-933c-6f1c4a5c9afd.png)

3. The cell after being edited while dynamic filter was enabled (with filter on):
![image](https://user-images.githubusercontent.com/108832807/225727485-ba20742b-db5a-41c7-ab42-96da92e0cc71.png)
The same cell with dark reader toggled off:
![image](https://user-images.githubusercontent.com/108832807/225727496-3bc65e94-eadb-48fd-a2d4-a76c733fc26d.png)

### Operating System

Windows 10

### Web Browser name and version

Google Chrome 110.0.5481.180 (Official Build) (64-bit)

### Dark Reader version

4.9.62 (Mar 16, 2023)

**Comment by Obsidianninja11** [comment]
I found the problem and what should be the fix, but I'm not sure how to fix it in dark reader since when I add this (which should fix it) dark reader breaks on google sheets.

```css
docs.google.com/spreadsheets

CSS
.input-box > .cell-input > span {
    --darkreader-inline-color: inherit !important;
}
```

<details><summary><h3>Screenshots</h3></summary>

The problem:
![image](https://github.com/user-attachments/assets/e733e53f-bdc1-4a28-8743-c405788509dc)
Fix (inherit accomplishes this):
![image](https://github.com/user-attachments/assets/8e83cbfa-2010-4545-9c6e-7c7c177ef1d1)
Trying to change it in darkreader devtools:
![image](https://github.com/user-attachments/assets/a3be0d4a-e076-4025-ad3b-289c869fd1cf)
</details>

**Comment by Obsidianninja11** [comment]
I just realized: the fix I sent in my previous comment only fixes the colors being set to white.
The correct fix would be to not add `data-darkreader-inline-color` from `.cell-input > span`
<details><summary><h3>Screenshots</h3></summary>

What to remove:
![image](https://github.com/user-attachments/assets/29150008-3ed2-4fab-94ae-a8fad2217d55)
After being fixed:
![image](https://github.com/user-attachments/assets/96e59135-83e5-4392-a99b-2e1cada6981e)
</details>

**Comment by SixelAlexiS90** [comment]
This is still an issue, I use the Dynamic filter and when I use Google Sheet the cells text change colors to custom all the time, which result in various shades of grey text (instead of full black).

**Comment by Obsidianninja11** [comment]
> This is still an issue, I use the Dynamic filter and when I use Google Sheet the cells text change colors to custom all the time, which result in various shades of grey text (instead of full black).
> 
> EDIT: just to give more info, the text color change in this case happen when you select a cell with a double click that have an hyperlink in it.

I gave up using dynamic filter in google sheets, started using a slightly modified filter+ that doesn't have this problem and still looks good.

**Comment by SixelAlexiS90** [comment]
> > This is still an issue, I use the Dynamic filter and when I use Google Sheet the cells text change colors to custom all the time, which result in various shades of grey text (instead of full black).
> > EDIT: just to give more info, the text color change in this case happen when you select a cell with a double click that have an hyperlink in it.
> 
> I gave up using dynamic filter in google sheets, started using a slightly modified filter+ that doesn't have this problem and still looks good.

Just gave up as well but how do you modify the Filter+? The sliders are locked and it's a bit too dark for me.

**Comment by Obsidianninja11** [comment]
> Just gave up as well but how do you modify the Filter+? The sliders are locked and it's a bit too dark for me.

I edited the css in the inversion fix editor (found in `More > All Settings > Advanced > Dev Tools` then search for `docs.google.com`)
I use +10 brightness, -15 contrast with some pretty subjective custom css I made.
<details><summary>My custom css and Image</summary>

![image](https://github.com/user-attachments/assets/428d0c45-d482-48ac-99fa-a0c2ba3bac29)

```css
================================

docs.google.com

INVERT
div[title="Profile"]
.kix-embeddedobject-image
.docs-branding-icon-img
.docs-homescreen-icon
.jfk-butterBar
.docs-ui-toast
[jsname="zz97Kb"]
.jfk-tooltip
.companion-tooltip
.waffle-collab-presence
.popout-indicator

NO INVERT
[aria-label="Search bar"]
.maps-place-item-preview-image
.docs-homescreen-grid-item-thumbnail
.docs-homescreen-templates-templateview-preview-overlay+img
.link-bubble-drive-thumbnail-image
.waffle-borderless-embedded-object-container > [style*="background-image: url"]

CSS
.jfk-tooltip, .waffle-namedtable-gridpill-table-name, .companion-tooltip, .gb_Oe {
    text-shadow: black 0px 0px;
}
.jfk-tooltip-arrow > [class^=jfk-tooltip-arrowimpl] {
    border-color: #1f1f1f transparent;
}
.docs-homescreen-tooltip {
    border: black;
    font-weight: 500;
}
.docs-gm :is(.docs-toolbar-more-bubble, .goog-menu), .annotation-editable,
.apps-search-popup-menu, .maps-place-item-preview-image {
    box-shadow: 0 2px 6px 2px rgb(255 255 255 / 100%) !important;
}
.waffle-dropdown-chip-renderer {
    box-shadow: 1px 2px 5px 2px rgb(255 255 255 / 100%) !important;
}
.docs-material-colorpalette-cell-hover .docs-material-colorpalette-colorswatch {
    box-shadow: none !important;
}
.docs-material-colorpalette-cell:hover .docs-material-colorpalette-colorswatch {
    box-shadow: 0 0 2.5px 1.5px #a6a6a6 !important;
}
html body {
    text-shadow: black 0 0 !important;
}
.cell-input {
    text-shadow: 0 0 0 !important;
}
body:has(.docs-homescreen-container)::-webkit-scrollbar-thumb {
    background-color: #33353a !important;
}
body:has(.docs-homescreen-container)::-webkit-scrollbar-track-piece {
    background-color: #131313 !important;
}
.docs-homescreen-fab {
    -webkit-box-shadow: 0 6px 10px 0 rgba(200, 200, 200, .14), 0 1px 18px 0 rgba(200, 200, 200, .12), 0 3px 5px -1px rgba(200, 200, 200, .2) !important;
    box-shadow: 0 6px 10px 0 rgba(200, 200, 200, .14), 0 1px 18px 0 rgba(200, 200, 200, .12), 0 3px 5px -1px rgba(200, 200, 200, .2) !important;
}
.modal-dialog-bg, .waffle-named-formulas-overlay-container {
    background-color: #fff !important;
    opacity: .6;
}
#docs-sidekick-gen-ai-promo-button-container {
    display: none;
}

================================
```
</details>
