### ISSUE TITLE
[Broken Website] OneDrive in a Browser - Action Bar 

### ISSUE THREAD

**Issue by timjobutler** [darkreader/darkreader#11417]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

When using Dark Reader in **Dynamic mode**, the action bar is washed out in white when selecting a file or folder in OneDrive. When using **Filter** or **Filter+** modes, the action bar is not washed out and the button text is visible.

The element that is affected is in the onedrive.live.com.txt file which is attached. Additionally, the element and style data are below. 
```html
<div class="ms-FocusZone css-97 ms-CommandBar root-108" role="menubar" aria-label="Command bar" data-focuszone-id="FocusZone3"><div role="group" class="ms-OverflowSet ms-CommandBar-primaryCommand primarySet-111"><div class="ms-OverflowSet-item item-112" role="none"><button type="button" role="menuitem" name="Share" title="Share the selected item with other people" data-automationid="shareCommand" class="ms-Button ms-Button--commandBar ms-CommandBarItem-link root-199" aria-label="Share" data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-200" data-automationid="splitbuttonprimary"><i data-icon-name="Share" aria-hidden="true" class="ms-Icon root-89 css-149 ms-Button-icon icon-202" style="font-family: FabricMDL2Icons;"></i><span class="ms-Button-textContainer textContainer-201"><span class="ms-Button-label label-203" id="id__122">Share</span></span></span></button></div><div class="ms-OverflowSet-item item-112" role="none"><button type="button" role="menuitem" name="Download" class="ms-Button ms-Button--commandBar ms-CommandBarItem-link root-199" data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-200" data-automationid="splitbuttonprimary"><i data-icon-name="download" aria-hidden="true" class="ms-Icon root-89 css-149 ms-Button-icon icon-202" style="font-family: FabricMDL2Icons;"></i><span class="ms-Button-textContainer textContainer-201"><span class="ms-Button-label label-203" id="id__125">Download</span></span></span></button></div><div class="ms-OverflowSet-item item-112" role="none"><button type="button" role="menuitem" name="Delete" data-automationid="deleteCommand" class="ms-Button ms-Button--commandBar ms-CommandBarItem-link root-199" aria-label="Delete" data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-200" data-automationid="splitbuttonprimary"><i data-icon-name="delete" aria-hidden="true" class="ms-Icon root-89 css-149 ms-Button-icon icon-202" style="font-family: FabricMDL2Icons;"></i><span class="ms-Button-textContainer textContainer-201"><span class="ms-Button-label label-203" id="id__439">Delete</span></span></span></button></div><div class="ms-OverflowSet-item item-112" role="none"><button type="button" role="menuitem" name="Move to" data-automationid="launchMovePickerCommand" class="ms-Button ms-Button--commandBar ms-CommandBarItem-link root-199" aria-label="Move to" data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-200" data-automationid="splitbuttonprimary"><i data-icon-name="FabricMoveToFolder" aria-hidden="true" class="ms-Icon root-89 css-206 ms-Button-icon icon-202" style="font-family: FabricMDL2Icons-5;"></i><span class="ms-Button-textContainer textContainer-201"><span class="ms-Button-label label-203" id="id__442">Move to</span></span></span></button></div><div class="ms-OverflowSet-item item-112" role="none"><button type="button" role="menuitem" name="Copy to" data-automationid="launchCopyPickerCommand" class="ms-Button ms-Button--commandBar ms-CommandBarItem-link root-199" aria-label="Copy to" data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-200" data-automationid="splitbuttonprimary"><i data-icon-name="Copy" aria-hidden="true" class="ms-Icon root-89 css-206 ms-Button-icon icon-202" style="font-family: FabricMDL2Icons-5;"></i><span class="ms-Button-textContainer textContainer-201"><span class="ms-Button-label label-203" id="id__445">Copy to</span></span></span></button></div><div class="ms-OverflowSet-item item-112" role="none"><button type="button" role="menuitem" name="Rename" data-automationid="renameCommand" class="ms-Button ms-Button--commandBar ms-CommandBarItem-link root-199" aria-label="Rename" data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-200" data-automationid="splitbuttonprimary"><i data-icon-name="rename" aria-hidden="true" class="ms-Icon root-89 css-206 ms-Button-icon icon-202" style="font-family: FabricMDL2Icons-5;"></i><span class="ms-Button-textContainer textContainer-201"><span class="ms-Button-label label-203" id="id__448">Rename</span></span></span></button></div><div class="ms-OverflowSet-overflowButton overflowButton-113"><button type="button" role="menuitem" class="ms-Button ms-Button--commandBar ms-Button--hasMenu ms-CommandBar-overflowButton root-199" aria-label="More" data-is-focusable="true" aria-expanded="false" aria-haspopup="true"><span class="ms-Button-flexContainer flexContainer-200" data-automationid="splitbuttonprimary"><i data-icon-name="More" aria-hidden="true" class="ms-Icon root-89 css-149 ms-Button-menuIcon menuIcon-305" style="font-family: FabricMDL2Icons;"></i></span></button></div></div><div role="group" class="ms-OverflowSet ms-CommandBar-secondaryCommand secondarySet-198"><div class="ms-OverflowSet-item item-112" role="none"><button type="button" role="menuitem" title="Clear selection" data-automationid="clearSelectionCommand" class="ms-Button ms-Button--commandBar ms-CommandBarItem-link root-299" data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-300" data-automationid="splitbuttonprimary"><i data-icon-name="Clear" aria-hidden="true" class="ms-Icon root-89 css-149 ms-Button-icon icon-202" style="font-family: FabricMDL2Icons;"></i><span class="ms-Button-textContainer textContainer-201"><span class="ms-Button-label label-301" id="id__451">1 selected</span></span><span class="alert_74fb7870">Use Enter key to clear selection.</span></span></button></div><div class="ms-OverflowSet-item item-112" role="none"><button type="button" role="menuitem" title="Switch view options" data-automationid="switchLayoutCommand" class="ms-Button ms-Button--commandBar ms-Button--hasMenu ms-CommandBarItem-link root-199" aria-label="Switch view options" data-is-focusable="true" aria-expanded="false" aria-haspopup="true" tabindex="0"><span class="ms-Button-flexContainer flexContainer-200" data-automationid="splitbuttonprimary"><i data-icon-name="list" aria-hidden="true" class="ms-Icon root-89 css-149 ms-Button-icon icon-202" style="font-family: FabricMDL2Icons;"></i><i data-icon-name="ChevronDownMed" aria-hidden="true" class="ms-Icon root-89 css-172 ms-Button-menuIcon menuIcon-204" style="font-family: FabricMDL2Icons-6; font-size: 12px;"></i></span></button></div><div class="ms-OverflowSet-item item-112" role="none"><button type="button" role="menuitem" title="Open the details pane" data-automationid="detailsCommand" class="ms-Button ms-Button--commandBar ms-CommandBarItem-link root-199" aria-controls="DetailsPane-77" aria-expanded="false" aria-label="Open the details pane" data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-200" data-automationid="splitbuttonprimary"><i data-icon-name="OpenPane" aria-hidden="true" class="ms-Icon root-89 css-206 ms-Button-icon icon-202" style="font-family: FabricMDL2Icons-5;"></i><span class="ms-Button-textContainer textContainer-201"><span class="ms-Button-label label-203" id="id__87">Info</span></span></span></button></div></div></div>
``` 

```css
    color-scheme: dark !important;
    --darkreader-neutral-background: #131516;
    --darkreader-neutral-text: #d8d4cf;
    --darkreader-selection-background: #004daa;
    --darkreader-selection-text: #e8e6e3;
    user-select: none;
    -webkit-tap-highlight-color: transparent;
    color: rgb(209, 205, 199);
    font-family: "Segoe UI", "Segoe UI Web (West European)", "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif;
    -webkit-font-smoothing: antialiased;
    font-size: 14px;
    font-weight: 400;
    display: flex;
    padding: 0px;
    height: 48px;
    border-radius: 8px;
    align-items: center;
    border-bottom: none;
    transition: background-color 467ms cubic-bezier(.1, .9, .2, 1);
    border-bottom-color: initial;
    animation-name: commandBarBoxShadowAnimation_c1ce1552;
    animation-duration: 267ms;
    animation-fill-mode: both;
    background-color: rgb(24, 26, 27);
``` 

I am happy to provide more info but since I am a novice, I will need some guidance as to what information to provide or what adjustments need to be tested in the Dark Reader Dev Tool.

Many thanks,
Tim

### Website Address

https://onedrive.live.com/

### Steps To Reproduce

1. Ensure that the Dynamic mode is set in Dark Reader
2. Log into OneDrive (https://onedrive.live.com/)
3. Select any item, either folder or file
4. The action bar for the selected item is washed out in white.

### Screenshots

![FILTER+-MODE-OneDrive-Action-Bar-White-Out](https://github.com/darkreader/darkreader/assets/37101212/36de0a60-cdf3-493a-874b-3fa0295eccc9)
![DYNAMIC-MODE-OneDrive-Action-Bar-White-Out](https://github.com/darkreader/darkreader/assets/37101212/9f626cfa-fad3-4738-81b2-8a1f1cd4711d)
![FILTER-MODE-OneDrive-Action-Bar-White-Out](https://github.com/darkreader/darkreader/assets/37101212/ac267c8b-063a-4495-a7ec-5fbe4fae5a9b)
[onedrive.live.com.txt](https://github.com/darkreader/darkreader/files/11780592/onedrive.live.com.txt)

### Operating System

Windows 11 64-bit

### Web Browser name and version

Chrome 114.0.5735.134

### Dark Reader version

4.9.63

**Comment by Yeah-Jack** [comment]
It should have been fixed in #11314.

**Comment by timjobutler** [comment]
Is there more backend code needed to be provided to assist with troubleshooting? I am not sure why #11314 wasn't fixed with the commit 🤷‍♂️

**Comment by Yeah-Jack** [comment]
> I am not sure why #11314 wasn't fixed with the commit 🤷‍♂️

The fix was only merged 14 hours ago.

**Comment by timjobutler** [comment]
Ah, I see. I look forward to checking the latest version. Thanks @Yeah-Jack

**Comment by timjobutler** [comment]
I have updated to the latest version of Dark Reader (4.9.64) but this issue is persisting. Running the latest version of Chrome (Version 114.0.5735.134).

Any clues as to why the command bar is still inverted?

![DYNAMIC-MODE-OneDrive-Action-Bar-White-Out](https://github.com/darkreader/darkreader/assets/37101212/3dda2e06-7e1b-42b0-abcd-074375f11d58)
