### ISSUE TITLE
DarkReader in Dynamic mode crashes / becomes unresponsive when loading a certain page.

### ISSUE THREAD

**Issue by absorber** [darkreader/darkreader#1158]
On Chromium, I can repeatedly crash the extension upon loading a certain page: https://downloads-eu.bitwig.com/stable/2.5/Release-Notes-2.5.html

This only seems to happen in Dynamic mode.

I made a video demonstrating this: https://youtu.be/F_NSCgKWNIk

On Firefox 65.0.1 (64-bit) I observed that it just consumed lots of CPU when loading that page, but it did not seem to crash the extension.
Furthermore, on my normal Chromium account, I can't seem to re-enable the extension anymore unless I restart Chromium.

Browser: Chromium v72.0.3626.121 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by Gusted** [comment]
Should be fixed by #2550

**Comment by absorber** [comment]
@gusted Nope, still crashes in Dynamic Mode.

Basically behavior is the same.

A more recent example: https://downloads-eu.bitwig.com/stable/3.2.7/Release-Notes-3.2.7.html

**Comment by absorber** [comment]
@Gusted could you please re-open the issue? It is still not fixed.

Also, I found out that https://tildes.net/ is causing DarkReader to consume massive amounts of RAM and CPU in Dynamic mode.
