### ISSUE TITLE
[Bug] Dark reader flashes white (white background) before loading the page. Dark Reader For Safari

### ISSUE THREAD

**Issue by bigplayer-ai** [darkreader/darkreader#12064]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

[Bug] Dark reader flashes white (white background) before loading the page. After the page is loaded it becomes dark/white, but this really hurts the eyes when switching between multiple new tabs.

### Website Address

*

### Steps To Reproduce

1) Open a page with a new tab
2) active that tab
3) see the pages starts with white then goes dark after the page is fully loaded.

### Expected Behavior

to start with dark background when starting webpages

### Actual Behavior

white background in dark mode

### Operating System

macOS Sonoma 14.2.1

### Web Browser name and version

Version 17.2.1 (19617.1.17.11.12)

### Dark Reader version

2.0.3

**Comment by waydabber** [comment]
+1

**Comment by Morgan1er** [comment]
Exact same problem here. 

I add this happens on both macOS and iOS.

**Comment by lothar-cell** [comment]
Any plans for fixing this? The extension has this exact problem on FireFox since 2018.

**Comment by pduchnovsky** [comment]
Would love to have this fixed.

**Comment by alexanderby** [comment]
I have found a solution and testing it now. An update should be available soon.

This is caused by a browser bug. While Chrome injects extension's scripts within 30 milliseconds, it takes Safari 250-500 milliseconds to do the same with this new WebExtensions API. That's why you see those terrible flashes. I've made an ugly, but working patch.

Thank you for your patience.

**Comment by bigplayer-ai** [comment]
> I have found a solution and testing it now. An update should be available soon.
> 
> This is caused by a browser bug. While Chrome injects extension's scripts within 30 milliseconds, it takes Safari 250-500 milliseconds to do the same with this new WebExtensions API. That's why you see those terrible flashes. I've made an ugly, but working patch.
> 
> Thank you for your patience.

Hello,

The Noir Application might offer a more refined solution. You can check with their developer here: [Noir - Dark Mode for Safari](https://apps.apple.com/us/app/noir-dark-mode-for-safari/id1592917505?mt=12). They are quite responsive.

---

For the update:

Thank you for the update. I appreciate the workaround and look forward to the official fix, I am reverting back to Dark Reader after long time haha (almost 8 months).

**Comment by alexanderby** [comment]
Please don't post links to those parasites.

**Comment by bigplayer-ai** [comment]
> Please don't post links to those parasites.

Sorry about that, and thanks for the update.

![2.1.0 changelog](https://github.com/user-attachments/assets/ace4468e-1ec6-4cb1-9886-a456d137b305)

However, the issue described in [[Bug] Hotkeys Not Working on macOS Safari](https://github.com/darkreader/darkreader/issues/13088) (#13088) still persists after the last update. The hotkeys should toggle the extension from auto to off.

**Comment by alexanderby** [comment]
> Additionally, the white flashes issue still persists. You can check this at [this login page](https://dig.shovelapp.io/-/login).

I think that's a separate issue, because I can see the text boxes being dark. Those large background images are processed asynchronously to prevent freezing during the initial loading (it's quite expensive operation to analyze such backgrounds).

**Comment by bigplayer-ai** [comment]
> > Additionally, the white flashes issue still persists. You can check this at [this login page](https://dig.shovelapp.io/-/login).
> 
> I think that's a separate issue, because I can see the text boxes being dark. Those large background images are processed asynchronously to prevent freezing during the initial loading (it's quite expensive operation to analyze such backgrounds).

I’d rather wait an extra two seconds than deal with those white flashes, which hurt the eyes in the dark. Please consider adding an experimental/extra option to fix this.

**Comment by gwcali** [comment]
Also still seeing white flashes after the 2.1 update. It's happening almost every time I click a link on one website to open another website in a new tab. 

iOS/iPadOS 17.6.1, MacOS 14.6.1.

**Comment by bigplayer-ai** [comment]
> Also still seeing white flashes after the 2.1 update. It's happening almost every time I click a link on one website to open another website in a new tab.
> 
> iOS/iPadOS 17.6.1, MacOS 14.6.1.

same and sometimes the page that is already loaded does not switch to dark mode especially after unlocking my MacBook at night...

**Comment by kernel-99** [comment]
I have the opposite problem, I get the white flashing during refresh only when not using the dark reader extension, if I enable it then the flashing during refresh doesn't occur anymore, so I guess this is on apple

**Comment by bigplayer-ai** [comment]
> I have the opposite problem, I get the white flashing during refresh only when not using the dark reader extension, if I enable it then the flashing during refresh doesn't occur anymore, so I guess this is on apple

Can you send a test link? Because with no dark reader, relying on dark mode from the websites, there is no white flashes for me…(you can try this at google.com)
Only with dark reader you can see the white flashes

**Comment by kernel-99** [comment]
sure, try this forum, make sure to toggle on the dark version by clicking on the op right user icon if it opens by default with the light version, once you are in the dark version just try refreshing and for me it flashes white, this happens with dark reader set to off or even disabled from the extensions

**Comment by bigplayer-ai** [comment]
> sure, try this forum, make sure to toggle on the dark version by clicking on the op right user icon if it opens by default with the light version, once you are in the dark version just try refreshing and for me it flashes white, this happens with dark reader set to off or even disabled from the extensions
> 
> https://forum.vsl.co.at/recent

This is specific website problem, this is unrelated to dark reader, make sure to report this to the website developers (website dark mode is not toggled at the correct time)….

there is still dark reader white flashes unrelated to the website you sent…

**Comment by bigplayer-ai** [comment]
> I have found a solution and testing it now. An update should be available soon.
> 
> This is caused by a browser bug. While Chrome injects extension's scripts within 30 milliseconds, it takes Safari 250-500 milliseconds to do the same with this new WebExtensions API. That's why you see those terrible flashes. I've made an ugly, but working patch.
> 
> Thank you for your patience.

after the last update pdf files from websites (non local) stopped being converted to black... it sometimes flashes black at the beginning but after some amount of time it gets reverted back to white...

**Comment by lothar-cell** [comment]
Safari STILL flashes when Dark Reader loads dark websites.

**Comment by lothar-cell** [comment]
Switched to the free Dark Night extension, as it managed to fix it already.

**Comment by lothar-cell** [comment]
Looks like the issue has been (mostly) resolved with the 2.1.2 update, can others confirm this?

**Comment by igorbzin** [comment]
Still have the same issue on newest Safari 26.0.1 and Dark Reader 2.1.2. Any ideas how to solve this issue?
