### ISSUE TITLE
White flash between page loads

### ISSUE THREAD

**Issue by heydojo** [darkreader/darkreader#1219]
When dark reader is turned on and installed into Firefox, there are white page load flashes between page loads where the all white default background is exposed before renders.
These flashes combined with dark reader have been giving me migraines as the page flip flops from over exposed bright white light to the mode dark reader creates when it does it's thing.

Is there any way dark reader could do something like change the default background in Firefox so that this flash does not occur?
It's really annoying.
Thanks. Great plugin BTW.

**Comment by Flaburgan** [comment]
+1 this is pretty annoying. To reproduce, simply close the current tab and reopen it with CTRL SHIFT T for example. When the page is loading (so before the DOM is there), its background is white.

![white-page](https://user-images.githubusercontent.com/930064/55462953-4a669d00-55f8-11e9-8227-6af71a90e710.gif)

**Comment by SemperRoto** [comment]
+1

I tried to fix it with the about:config setting browser.display.background_color and set it to #000000 but while it makes a simple about:blank page black it does not help with the in-between white screens described here.

**Comment by King-Aardvark** [comment]
From my understanding Firefox Quantum restricted what web extensions can do to the browser and protected pages.

Only way to fix this issue is to use https://overdodactyl.github.io/ShadowFox/.

Bit weird to setup but works beautifully.

**Comment by CtrlShiftEscape** [comment]
I use this
```css
#tabbrowser-tabpanels {
  background: var(--toolbar-bgcolor) !important;
}
```

**Comment by h-2** [comment]
Neither ShadowFox nor manual code in userContent.css fix the annoying flash for me. It's a real shame because with these flashes the extension has the opposite of the intended effect: it's even worse for the eyes when you work in the dark. In general it results in me deactivating the plug-in and just reducing brightness of the screen, but I would much prefer the other way around.

**Comment by githubtefo** [comment]
> Neither ShadowFox nor manual code in userContent.css fix the annoying flash for me. It's a real shame because with these flashes the extension has the opposite of the intended effect: it's even worse for the eyes when you work in the dark. In general it results in me deactivating the plug-in and just reducing brightness of the screen, but I would much prefer the other way around.

The @CtrlShiftEscape code works for me. I added to `userChrome.css`. I also added
`@-moz-document url-prefix(about:blank) {*{background-color:#333333;}}` to `userContent.css`, which may be contributing.

**Comment by Flaburgan** [comment]
It does work, indeed.

**Comment by mashuma** [comment]
Another way that I prefer, which is very close to what @githubtefo has suggested, is to use https://github.com/overdodactyl/ShadowFox

It not only solves this problem, but adds whole lot of dark in other places of the browswer.

**Comment by lordblackfire** [comment]
Oddly enough, setting the desktop theme to a dark theme fixed it for me. I'm using GNOME and changing the theme to yaru-dark did it.

**Comment by victor9000** [comment]
As stated above, the userContent.css method works, but it requires a few steps that are not immediately obvious.
1. Identify your Profile Directory at `Help > Troubleshooting Information`
2. Go to your Profile Directory and create a folder named `chrome`
3. Create your `userChrome.css` file inside the `chrome` folder
4. Add the following to `userChrome.css`
```
#tabbrowser-tabpanels {
  background: var(--toolbar-bgcolor) !important;
}
```
5. Follow the instructions below to enable the use of userContent.css in Firefox 69+
https://www.ghacks.net/2019/05/24/firefox-69-userchrome-css-and-usercontent-css-disabled-by-default/
6. Restart Firefox

**Comment by Gusted** [comment]
Darkreader already prevent further white flashes at document_staet after some checks of course... The white flash your seeing is from making a connection TLS handshake etc. You can fill an bug report by Firefox as setting the appearance setting to dark doesn't make the white flash dark... So far I know.

**Comment by tmpm697** [comment]
This page might help you: https://support.mozilla.org/en-US/questions/1269392

**Comment by githubtefo** [comment]
> This page might help you: https://support.mozilla.org/en-US/questions/1269392
Thanks for the contribution.
It did not make any differences the solution suggested here for me.

**Comment by tmpm697** [comment]
Yes, seem it didn't fix the issue, but from what I've tested, even with just firefox + darkreader the issue happens, so some where need to improve, ether from ff for better dark support and stop hardcode colorcode into codebase or darkreader comes up with a solution.

**Comment by Gusted** [comment]
Darkreader solutions is already their but the white flash is from Firefox itself that needs to get the site and request it etc. Use ShadowFox :)

**Comment by tmpm697** [comment]
Use ShadowFox breaks darkreader or force parts of dynamic but if you consider it's necessary to solve the issue the go for it, I've tested with SahdowFox, it does fix the issue but it changes the look of default rendered a bit.

How to import css part of ShadowFox the just fix the issue instead of loading its whole css?

**Comment by githubtefo** [comment]
Actually I have ShadowFox too, and not all of the white flashes are fixed (probably the ones that @Gusted mentioned about connection TLS handshakes are still there).
Thanks.-

**Comment by tmpm697** [comment]
Yes, I confirm, use shadowfox still have issue, this issue breaks down the whole dark mode experience dues to flash white page.

I can 100% produce this issue by loading bunch of pages then create new slow load page (image, txt, css..) then flash switch to another tab, wait for the page loaded and switch back, now you can 100% observe full/partial white page.

This is due to pages contain large media ..etc that when loading page in the time darkreader did'nt render it fast enough, firefox will render that parts with white to indicate it's not loaded or not avail to display yet.

I believe this issue can be resolved if firefox comes with the sense of dark mode and support at least display all protected components in dark.

**Comment by tmpm697** [comment]
But I observe this issue a lot recently, did some new updates cause that? @Gusted

**Comment by Gusted** [comment]
Not that I know we didn't change to our code to cancel rendering and try to prevent flashes....

**Comment by Gusted** [comment]
Then you should create a bug issue as we already prevent so fast as possible white flashes. But we don't have control when the DOM is not yet in memory or isn't fetched from the server

**Comment by Gusted** [comment]
Firefox had resolved this already if Firefox detects your using dark mode it will gave a dark-ish flash that should do the trick.
Otherwise try `Create ui.systemUsesDarkTheme = 1 in about:config`

**Comment by klcheungaj1225** [comment]
If using Firefox, go to preference -> fonts and colors -> colors, setting the colors and choosing "always".
This should solve white flash issue.

**Comment by tmpm697** [comment]
@klcheungaj1225 should be opposite your suggestion to make it work. 
Always -> never.

**Comment by MR-Diamond** [comment]
> If using Firefox, go to preference -> fonts and colors -> colors, setting the colors and choosing "always".
> This should solve white flash issue.

> @klcheungaj1225 should be opposite your suggestion to make it work.
> Always -> never.

None of these suggestions resolve the issue. (Firefox 79.0)

**Comment by tmpm697** [comment]
@MR-Diamond yeah, confirm that.

I give up on this issue.

**Comment by Gusted** [comment]
> I give up on this issue.

Have faith :) #3533

**Comment by rishabhdeepsingh** [comment]
Even if we scroll fast it will also show a white screen.

**Comment by Gusted** [comment]
> Even if we scroll fast it will also show a white screen.

Ho, that's rendering and that is 100% up to the browser itself. If you think this a serious issue and 100% reproduce-able alongside other website you can open up a new issue and I will have look.

**Comment by klcheungaj1225** [comment]
> 
> 
> > If using Firefox, go to preference -> fonts and colors -> colors, setting the colors and choosing "always".
> > This should solve white flash issue.
> 
> > @klcheungaj1225 should be opposite your suggestion to make it work.
> > Always -> never.
> 
> None of these suggestions resolve the issue. (Firefox 79.0)

It works for me on Firefox 79.0 and Windows 10 by changing background and font color.
I also need to set browser.in-content.dark-mode = true and ui.systemUsesDarkTheme = 1 in about:config.
However, Firefox's colors settings would overwrite Dark Reader in many websites but it is not comfortable as Dark Reader dynamic mode.

Now I switch to Chromium Edge when I want to use Dark Reader. It works well on Chromium Edge when using dark theme and setting Force Dark Mode for Web Contents = Enabled in edge://flags.

**Comment by MR-Diamond** [comment]
> It works for me on Firefox 79.0 and Windows 10

Doesn't works for me and for other people as reported in this discussion.

**Comment by Gusted** [comment]
Hi!

Dark reader v4.9.17 has been released that has the fix that fixes this issue 🎉.
To make sure you are on the latest version to make sure this is the case.
First, we should make sure your on the new user interface of Dark reader, by doing:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

This should have activated the new user interface and should look like this: ![](https://i.imgur.com/cJJwSrY.png). Make sure to pay attention to the bottom text that says the current version. If it states an older version e.g. 4.9.16 I suggest to remove the extension and re-install it trough https://darkreader.org/ so it will be forced to download the latest version.
If this fix still indicates this issue let me know and hopefully improvements can be made!

Regards,
Gusted

**Comment by carlogarro** [comment]
@Gusted , it does not matter I do, it always installs the version 4.9.16 even though in the addons-firefox webpage it says: 

Version
    4.9.21
Size
    663.12 KB
Last updated
    6 days ago (Sep 26, 2020)

**Comment by Gusted** [comment]
> @Gusted , it does not matter what I do, it always installs the version 4.9.16 even though in the addons-firefox webpage it says:
> 
> ```
> Version
>     4.9.21
> Size
>     663.12 KB
> Last updated
>     6 days ago (Sep 26, 2020)
> ```

Try to create a fresh new profile and test it on their, it might be some cached add-on that's being used. If the issue persist a bug over [Mozilla's bug tracker](https://bugzilla.mozilla.org/home) can be made.

**Comment by createyourpersonalaccount** [comment]
I had the same issue with Dark Reader version 4.9.23 on Linux: If I rapidly opened too many tabs, I'd get white flashes. I'd get white flashes if I visited Google's website (then it'd turn dark). I fixed it by adding `ui.systemUsesDarkTheme = 1` on `about:config`. Perhaps Dark Reader should set this variable itself?

**Comment by Gusted** [comment]
> I fixed it by adding `ui.systemUsesDarkTheme = 1` on `about:config`.

This means the system was not preferred to have a dark theme and therefore Dark Reader won't prevent flashes.

> Perhaps Dark Reader should set this variable itself?

1. Not possible for an add-on.
2. This also causes a lot of other unexpected behaviour for the User.

**Comment by createyourpersonalaccount** [comment]
Okay then. Thank you for Dark Reader :)

**Comment by MR-Diamond** [comment]
I'm still experience this issue, but doesn't occurs on every website (eg: github loads fine on Chromium but the white flash occurs on Firefox). But some sites (I attach gif recordings) presents the wite flash for oth browsers ehrn using Dark Reader.

Chromium 87.0.4280.66
Firefox 83.0
Manjaro Linux, but occurs also on Windows and Mac.

As I set Dark Reader to "Off", white flashes are not visible. I also tried a lot of suggested workarounds but nothing helps.

![white-flash2](https://user-images.githubusercontent.com/32249442/99886808-c5525080-2c3f-11eb-9fb0-a4b0426b3184.gif)
![white-flash1](https://user-images.githubusercontent.com/32249442/99886811-c8e5d780-2c3f-11eb-9e67-047f1ce6e287.gif)

**Comment by VeryStrongFingers** [comment]
> https://github.com/darkreader/darkreader/issues/1219#issuecomment-560168272 Oddly enough, setting the desktop theme to a dark theme fixed it for me. I'm using GNOME and changing the theme to yaru-dark did it.

This was the only thing that worked for me, using a dark GNOME theme (Ubuntu 18.04).
ShadowFox, userContent.css/userChrome.css had no effect

**Comment by kitech** [comment]
archlinux firefox 84, still have this issue, using latest dark reader 4.9.26

**Comment by Azraelle** [comment]
Same. It's getting pretty annoying that i have to troubleshoot it every few months.

**Comment by Gusted** [comment]
Move the discussion over to #469
