### ISSUE TITLE
Dark mode doesn't work on YouTube

### ISSUE THREAD

**Issue by xin12pzx24** [darkreader/darkreader#1266]
Today, i found darkreader doesn't work on YouTube. i don't know why.
But i fix it by replacing the default settings in darkreader.
If you don't want to fix it yourself, you can use my solution.
Or maybe you can take some time to fix it.
It may be a bit lengthy, but it's a temporary solution.

**Code below:**
```
youtube.com

INVERT
#checkmark
.ytp-volume-slider-handle
.toggle-bar.style-scope.paper-toggle-button
.align-by-text.style-scope.ytd-comment-replies-renderer
g#youtube-red-paths
#like-bar
.yt-simple-endpoint.style-scope.ytd-grid-video-renderer
.title.style-scope.ytd-guide-entry-renderer
.style-scope.ytd-guide-signin-promo-renderer
#video-title.style-scope.ytd-compact-video-renderer
.more-button.style-scope.ytd-comment-renderer
#submenu.menu-container.style-scope.ytd-multi-page-menu-renderer
#content.style-scope.ytd-expander
#author-text.yt-simple-endpoint.style-scope.ytd-comment-renderer
#simplebox-placeholder
#upload-info

CSS
#textarea, paper-button {
    color: ${black} !important;
}

.style-scope.ytd-page-manager, 
.style-scope.ytd-masthead, 
.style-scope.ytd-guide-renderer, 
#header.style-scope.ytd-app, 
#columns.style-scope.ytd-watch-flexy, 
.style-scope.ytd-popup-container,
.style-scope.ytd-searchbox,
#label.style-scope.ytd-toggle-theme-compact-link-renderer,
#label.style-scope.ytd-compact-link-renderer,
#subtitle.style-scope.ytd-compact-link-renderer,
#video-title.style-scope.ytd-compact-playlist-renderer,
#video-title.style-scope.ytd-compact-radio-renderer{
    background-color: black !important;   
    color: ${black} !important;   
}
```

**Comment by alexanderby** [comment]
Hi, please update Dark Reader up to 4.7.11, if you already have the latest version, reset your changes in Dev Tools.

**Comment by MobiuSRIT** [comment]
Hail 4.7.11 -- I was going mad after youtube pushed it's new light/dark theming and dark reader stopped.  I'm so happy this is working again in this version.  Thank you.

**Comment by alexanderby** [comment]
@MobiuSRIT Maybe you have to reset changes in Dev Tools. By the way, it seems that today they reverted the change.

**Comment by MobiuSRIT** [comment]
Yeah, it looks like dark reader is back working with youtube again.  Who knows how long it will stick.  Just goes to show how heavily I'm relying on Dark Reader -- when a site goes white, it's shocking.

**Comment by niudiewei** [comment]
the same thing happened on my computer yesterday.

**Comment by socalcr** [comment]
Same issue occurred for me today. Look like it's broken. I did reset through dev options but youtube is no longer going dark.

I did use this person's string and it had fixed the issue.

**Comment by xin12pzx24** [comment]
Now, you can update Dark Reader up to 4.7.11, or reset your changes in Dev Tools. it will work!!
Just like @alexanderby said.
### But !!!
if you login your google account, it would not work.
Now, it depends on your settings in your Google Account.
Tested in Google Chrome Incognito Mode.

**Comment by alexanderby** [comment]
I've noticed some unstable behavior. I hope with the latest 4.7.12 version the problem should be fixed.

**Comment by darkphoenixstar** [comment]
Everything depends on the Browser you use.  As I know, you can fix the dark/white mode using the Console Tab in Chrome. It is enough to open the Developers' Menu and open the console tab, put this line document.cookie=”VISITOR_INFO1_LIVE=fPQ4jCL6EiE; path=/” and press enter. After this, you can change the settings directly in your Youtube account. Full guide for some browsers is here [https://rocketfiles.com/articles/how-to-activate-youtube-dark-mode-in-chrome-firefox-edge-opera.](https://rocketfiles.com/articles/how-to-activate-youtube-dark-mode-in-chrome-firefox-edge-opera.)

**Comment by mvastola** [comment]
FYI, with the latest version the issue with the YouTube volume slider is still present.
I'm about to make a pull request to fix this.
![neb6](https://user-images.githubusercontent.com/599767/64929291-69e23280-d7f2-11e9-929f-fb66ae69e341.png)

**Comment by Gusted** [comment]
F i x e d
