### ISSUE TITLE
Unable to interact with check boxes on Protonmail

### ISSUE THREAD

**Issue by geeknik** [darkreader/darkreader#1384]
While using Firefox 68 + DarkReader 4.7.12, I'm unable to toggle check boxes on Protonmail. Instead of selecting the item like normally, it just acts like a click and opens the email. I'm also unable to star any emails.

![Screenshot_2019-06-18 (17) Inbox geeknik protonmail ch ProtonMail](https://user-images.githubusercontent.com/466878/59704153-16475500-91c1-11e9-8431-0ff574c6cbf9.png)

**Comment by geeknik** [comment]
I reset the Protonmail theme to defaults under Settings->Appearance and it fixed the interaction issue.

**Comment by ShalokShalom** [comment]
I have tried this too and mine are still locking not very smooth. 
Same as in your screenshot. 
Text reads fine now, thanks.

**Comment by mikerouxfr** [comment]
Same issue even after using the reset to default trick.

I guess it is because **DarkReader** use `background-color` instead of `background` in the injected inline CSS.

-----

Here is the custom set rule I used to fix the issue:
```css
================================

mail.protonmail.com

CSS
.customCheckbox-input + .customCheckbox-mask {
    background: #262829;
}
```

Click your **DarkReader** shortcut and find the `🛠 Dev Tools` (name may differ in other locales; Then, insert the rule somewhere in the file (below beta.protonmail.com for example).

**Comment by Gusted** [comment]
I've merged a PR(#4065) to fix this for all users who uses protonmail so it will become a permanent change as the devtools will be overridden after an update.

**Comment by aha999** [comment]
Hi! this is still an issue with protonmail, what can we do ? Protonmail doesn't have a dark theme AFAIK

**Comment by ShalokShalom** [comment]
This is the current situation. 

![Screenshot_20210327_142222](https://user-images.githubusercontent.com/6344099/112722117-e5549200-8f07-11eb-8b52-1c075fcf3a35.png)

Its possible to interact, the mark is barely visible.

**Comment by slmb3** [comment]
#5343 will make the checkboxes appear usable again. If you don't want to wait, delete the `mail.protonmail.com` block in Dark Reader > Dev tools for immediate fix.

**Comment by slmb3** [comment]
@aha999 @ShalokShalom what browser are you both using?

**Comment by ShalokShalom** [comment]
Firefox desktop

**Comment by slmb3** [comment]
I'm not sure what happened, but I put back in the `mail.protonmail.com` fix, and it's working again :/
