### ISSUE TITLE
[Broken Website] [shopee.com] Opening a link in a new background tab will cause the site to appear blank.

### ISSUE THREAD

**Issue by AzimsTech** [darkreader/darkreader#14435]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [x] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Most likely, what happens is that when you open a product link in a background tab, it causes the theme generation mode to switch from Dynamic to Static mode, which makes the page appear blank.

### Website Address

https://shopee.com/

### Steps To Reproduce

1. Navigate to [shopee.com](shopee.com)

2. Scroll down and Ctrl + Click on any product

### Screenshots

![Image](https://github.com/user-attachments/assets/a2196c34-7225-4ad5-9018-7e5d12092575)

### Operating System

Windows 11

### Web Browser name and version

Chrome (138.0.7204.63)  & Firefox (140.0.2)

### Dark Reader version

4.9.106

### Additional Context

It requires a login and is region-dependent. Accessing Shopee.com redirects to a localized version based on geo-location:  

|  URL                         | Country      |
|---------------------------------------------|--------------|
| [https://shopee.sg](https://shopee.sg)       | Singapore    |
| [https://shopee.co.id](https://shopee.co.id) | Indonesia    |
| [https://shopee.co.th](https://shopee.co.th) | Thailand     |
| [https://shopee.com.my](https://shopee.com.my) | Malaysia     |
| [https://shopee.vn](https://shopee.vn)       | Vietnam      |
| [https://shopee.ph](https://shopee.ph)       | Philippines  |
| [https://shopee.com.br](https://shopee.com.br) | Brazil       |
| [https://shopee.com.mx](https://shopee.com.mx) | Mexico       |
| [https://shopee.com.co](https://shopee.com.co) | Colombia     |
| [https://shopee.cl](https://shopee.cl)       | Chile        |
| [https://shopee.tw](https://shopee.tw)       | Taiwan       |

**Comment by Myshor** [comment]
Can not reproduce. You did not set any theme setting separate for shopee local page, didn't you?

Because it's the only possible reason IMHO why it could change Dynamic to Static after URL change.

**Comment by AzimsTech** [comment]
@Myshor It's not in Static mode. Its behavior is similar to what you experience in Static mode. So, the dynamic theme isn't working. Sorry, I didn't explain that well.

proxy.js is not loaded
![Image](https://github.com/user-attachments/assets/b8fb2ba3-bf94-4099-b32c-c492267ff4e2)

**Comment by Myshor** [comment]
I was able to reproduce it 2 times out of 15 tries.
First I forgot to check console in Browser Developer Tools. So I tried again and after 10 tries it happened again.

This time I have copied what I found in console:
```
20:10:37.000 Error: 
[sws.3bbc4855727c75b9.2023.js:1:388161](https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/sws.3bbc4855727c75b9.2023.js)
20:10:37.032 
<div>
​accessKey: ""
​accessKeyLabel: ""
​align: ""
​ariaActiveDescendantElement: null
​ariaAtomic: null
​ariaAutoComplete: null
​ariaBrailleLabel: null
​ariaBrailleRoleDescription: null
​ariaBusy: null
​ariaChecked: null
​ariaColCount: null
​ariaColIndex: null
​ariaColIndexText: null
​ariaColSpan: null
​ariaControlsElements: null
​ariaCurrent: null
​ariaDescribedByElements: null
​ariaDescription: null
​ariaDetailsElements: null
​ariaDisabled: null
​ariaErrorMessageElements: null
​ariaExpanded: null
​ariaFlowToElements: null
​ariaHasPopup: null
​ariaHidden: null
​ariaInvalid: null
​ariaKeyShortcuts: null
​ariaLabel: null
​ariaLabelledByElements: null
​ariaLevel: null
​ariaLive: null
​ariaModal: null
​ariaMultiLine: null
​ariaMultiSelectable: null
​ariaOrientation: null
​ariaOwnsElements: null
​ariaPlaceholder: null
​ariaPosInSet: null
​ariaPressed: null
​ariaReadOnly: null
​ariaRelevant: null
​ariaRequired: null
​ariaRoleDescription: null
​ariaRowCount: null
​ariaRowIndex: null
​ariaRowIndexText: null
​ariaRowSpan: null
​ariaSelected: null
​ariaSetSize: null
​ariaSort: null
​ariaValueMax: null
​ariaValueMin: null
​ariaValueNow: null
​ariaValueText: null
​assignedSlot: null
​attributes: NamedNodeMap []
​autocapitalize: ""
​autocorrect: true
​autofocus: false
​baseURI: "https://shopee.com.my/Non-Stick-Soup-Pot-Induction-Stew-Pan-Induction-Pot-Non-Stick-Kaserola-Gas-Universal-26-28-30CM-i.1242421617.29061749529?sp_atk=ea7da668-a959-4f00-be6a-8a734cc125e2&xptdk=ea7da668-a959-4f00-be6a-8a734cc125e2"
​childElementCount: 0
​childNodes: NodeList []
​children: HTMLCollection { length: 0 }
​classList: DOMTokenList []
​className: ""
​clientHeight: 0
​clientLeft: 0
​clientTop: 0
​clientWidth: 0
​contentEditable: "inherit"
​currentCSSZoom: 1
​dataset: DOMStringMap(0)
​dir: ""
​draggable: false
​enterKeyHint: ""
​firstChild: null
​firstElementChild: null
​hidden: false
​id: 
​inert: false
​innerHTML: ""
​innerText: ""
​inputMode: ""
​isConnected: false
​isContentEditable: false
​lang: ""
​lastChild: null
​lastElementChild: null
​localName: "div"
​namespaceURI: "http://www.w3.org/1999/xhtml"
​nextElementSibling: null
​nextSibling: null
​nodeName: "DIV"
​nodeType: 1
​nodeValue: null
​nonce: ""
​offsetHeight: 0
​offsetLeft: 0
​offsetParent: null
​offsetTop: 0
​offsetWidth: 0
​onabort: null
​onanimationcancel: null
​onanimationend: null
​onanimationiteration: null
​onanimationstart: null
​onauxclick: null
​onbeforeinput: null
​onbeforematch: null
​onbeforetoggle: null
​onblur: null
​oncancel: null
​oncanplay: null
​oncanplaythrough: null
​onchange: null
​onclick: null
​onclose: null
​oncontentvisibilityautostatechange: null
​oncontextlost: null
​oncontextmenu: null
​oncontextrestored: null
​oncopy: null
​oncuechange: null
​oncut: null
​ondblclick: null
​ondrag: null
​ondragend: null
​ondragenter: null
​ondragexit: null
​ondragleave: null
​ondragover: null
​ondragstart: null
​ondrop: null
​ondurationchange: null
​onemptied: null
​onended: null
​onerror: null
​onfocus: null
​onformdata: null
​onfullscreenchange: null
​onfullscreenerror: null
​ongotpointercapture: null
​oninput: null
​oninvalid: null
​onkeydown: null
​onkeypress: null
​onkeyup: null
​onload: null
​onloadeddata: null
​onloadedmetadata: null
​onloadstart: null
​onlostpointercapture: null
​onmousedown: null
​onmousemove: null
​onmouseout: null
​onmouseover: null
​onmouseup: null
​onpaste: null
​onpause: null
​onplay: null
​onplaying: null
​onpointercancel: null
​onpointerdown: null
​onpointerenter: null
​onpointerleave: null
​onpointermove: null
​onpointerout: null
​onpointerover: null
​onpointerrawupdate: null
​onpointerup: null
​onprogress: null
​onratechange: null
​onreset: null
​onresize: null
​onscroll: null
​onscrollend: null
​onsecuritypolicyviolation: null
​onseeked: null
​onseeking: null
​onselect: null
​onselectionchange: null
​onselectstart: null
​onslotchange: null
​onstalled: null
​onsubmit: null
​onsuspend: null
​ontimeupdate: null
​ontoggle: null
​ontransitioncancel: null
​ontransitionend: null
​ontransitionrun: null
​ontransitionstart: null
​onvolumechange: null
​onwaiting: null
​onwebkitanimationend: null
​onwebkitanimationiteration: null
​onwebkitanimationstart: null
​onwebkittransitionend: null
​onwheel: null
​outerHTML: "<div></div>"
​outerText: ""
​ownerDocument: HTMLDocument https://shopee.com.my/Non-Stick-Soup-Pot-Induction-Stew-Pan-Induction-Pot-Non-Stick-Kaserola-Gas-Universal-26-28-30CM-i.1242421617.29061749529?sp_atk=ea7da668-a959-4f00-be6a-8a734cc125e2&xptdk=ea7da668-a959-4f00-be6a-8a734cc125e2
​parentElement: null
​parentNode: null
​part: DOMTokenList []
​popover: null
​prefix: null
​previousElementSibling: null
​previousSibling: null
​role: null
​scrollHeight: 0
​scrollLeft: 0
​scrollLeftMax: 0
​scrollTop: 0
​scrollTopMax: 0
​scrollWidth: 0
​shadowRoot: null
​slot: ""
​spellcheck: false
​style: CSS2Properties(0)
​tabIndex: -1
​tagName: "DIV"
​textContent: ""
​title: ""
​translate: true
​<get id()>: function ()​
<prototype>: HTMLDivElementPrototype { align: Getter & Setter, … }
```
```
20:10:36.877 InstallTrigger jest przestarzałe i zostanie usunięte w przyszłości. sws.3bbc4855727c75b9.2023.js line 1 > eval:1:1
20:10:36.893 WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. sws.3bbc4855727c75b9.2023.js:1:591149
20:10:37.000 Error: 
sws.3bbc4855727c75b9.2023.js:1:388161
20:10:37.032
<div>
sws.3bbc4855727c75b9.2023.js:1:388161
20:10:37.059 WebGL warning: linkProgram: Must have a compiled fragment shader attached: Missing shader.
20:10:37.059 WebGL warning: uniform setter: No active linked Program.
20:10:37.444 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:37.444 WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. 2.28.921.js:1:348704
20:10:37.639 Typ zdarzenia „onmozfullscreenchange” jest przestarzały. sws.3bbc4855727c75b9.2023.js:1:393307
20:10:37.639 Typ zdarzenia „onmozfullscreenerror” jest przestarzały. sws.3bbc4855727c75b9.2023.js:1:393307
20:10:37.688 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://df.infra.shopee.com.my/v2/shpsec/web/report” (nieudane żądanie CORS). Kod stanu: (null).
20:10:37.709 TypeError: can't access property 9 of null
2.28.921.js:1:348704
20:10:37.859 Uprawnienie do wyświetlania powiadomień może być żądane jedynie z wnętrza krótko działającej procedury obsługi zdarzeń generowanych przez użytkownika. Non-Stick-Soup-Pot-Induction-Stew-Pan-Induction-Pot-Non-Stick-Kaserola-Gas-Universal-26-28-30CM-i.1242421617.29061749529
20:10:37.933 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:37.964 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:38.056 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null). 2
20:10:38.913 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:38.991 TypeError: can't access property 9 of null
2.28.921.js:1:348704
20:10:39.033 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:39.237 Automatyczne odtwarzanie jest możliwe jedynie po wyrażeniu zgody przez użytkownika, gdy strona zostanie aktywowana przez użytkownika lub treść jest wyciszona. Non-Stick-Soup-Pot-Induction-Stew-Pan-Induction-Pot-Non-Stick-Kaserola-Gas-Universal-26-28-30CM-i.1242421617.29061749529
20:10:39.260 TypeError: can't access property 9 of null
2.28.921.js:1:348704
20:10:39.337 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:39.439 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://df.infra.shopee.com.my/v2/shpsec/web/report” (nieudane żądanie CORS). Kod stanu: (null).
20:10:39.464 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:10:39.470 MiniChat Build Time:  Thu Jun 26 2025 17:40:29 GMT+0800 (Singapore Standard Time) minichat.js:1:6996
20:10:39.484 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:10:39.791 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:39.943 Ciasteczko „CTOKEN” zostało odrzucone z powodu nieprawidłowej domeny. 2 login
20:10:40.054 Ciasteczko „CTOKEN” zostało odrzucone z powodu nieprawidłowej domeny. 2 login
20:10:40.064 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:40.125 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:40.158 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:40.319 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:40.350 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:10:40.469 TypeError: can't access property 9 of null
2.28.921.js:1:348704
20:10:41.410 Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
20:10:41.503 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null). 4
20:10:47.901 Błąd mapy źródła: Error: NetworkError when attempting to fetch resource.
URL zasobu: https://deo.shopeemobile.com/shopee/modules-federation/live/0/shopee__web_enhance_sap/2.28.921.js
URL mapy źródła: https://files.webfe.shopee.io/modules-federation/bundle/0/shopee__web_enhance_sap/2.28.921.js.map
20:10:48.529 Error: Promised response from onMessage listener went out of scope 2 build.js:2:92650
20:10:48.546 |-- 新加上报点上报阶段:  LOAD_RESOURCE , 耗时为: 0, 数据： 
Object {  }
service.45ec8932feb7186438f3.js:1:26878
20:10:48.657 Błąd mapy źródła: Error: request failed with status 403
Stack in the worker:networkRequest@resource://devtools/client/shared/source-map-loader/utils/network-request.js:43:9

URL zasobu: https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/sws.3bbc4855727c75b9.2023.js
URL mapy źródła: https://sourcemap.webfe.shopeemobile.com/pcmall-static/_/sws.3bbc4855727c75b9.2023.js.map
20:10:53.539 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:10:53.543 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:10:56.987 |-- 新加上报点上报阶段:  RENDER_HOME_PAGE , 耗时为: 0, 数据： 
Object { isSidebar: false }
service.45ec8932feb7186438f3.js:1:26878
20:11:09.578 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:11:09.590 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:11:29.602 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:11:29.607 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:11:39.290 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:11:39.349 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:11:51.533 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:11:51.536 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:12:11.993 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:12:11.996 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:12:32.331 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:12:32.334 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:12:41.518 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:12:41.584 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:12:52.662 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:12:52.665 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:13:13.205 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:13:13.209 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:13:33.612 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:13:33.615 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:13:41.749 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:13:41.823 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:13:54.088 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:13:54.092 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:14:14.556 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:14:14.561 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:14:35.907 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:14:35.910 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:14:42.001 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:14:42.065 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:14:56.353 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:14:56.357 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:15:16.744 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:15:16.747 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:15:37.274 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:15:37.278 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:15:42.334 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:15:42.401 TypeError: can't access property 9, le(...) is null
2.28.921.js:1:348704
20:15:57.309 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:15:57.312 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:16:17.331 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
20:16:17.335 Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://ubt.tracking.shopee.com.my/v4/event_batch” (nieudane żądanie CORS). Kod stanu: (null).
```

After manual refresh it loads fine and... shows exactly the same things in console. 😅

Leaving it open. Maybe @alexanderby will have possibility to reproduce it too and think what exactly can be done with this issue.

**Comment by AzimsTech** [comment]
This has been fixed in the latest release https://github.com/darkreader/darkreader/commit/9f493b509f430ce02f60b8e09be4bbf28369dfcb
Thanks :+1:

**Comment by alexanderby** [comment]
Maybe you have some other extensions installed, that add extra buttons into those websites? We fixed some compatibility issues in the latest release (4.9.108).

**Comment by AzimsTech** [comment]
@alexanderby No, I have created a new, unmodified Chrome profile and only added the Dark Reader extension, but the issue still persists in that version (4.9.106). This happened in both Firefox and Chrome.
