### ISSUE TITLE
[Safari] Sepia is 100%

### ISSUE THREAD

**Issue by hologerry** [darkreader/darkreader#1684]
The dark theme of the newest version on Safari looks weird.
<img width="1703" alt="Screen Shot 2019-11-01 at 12 39 07" src="https://user-images.githubusercontent.com/11660168/68002648-c74c1900-fca4-11e9-8db4-c786717bd896.png">
<img width="1703" alt="Screen Shot 2019-11-01 at 12 39 17" src="https://user-images.githubusercontent.com/11660168/68002650-cadfa000-fca4-11e9-8d81-f6eec5022b62.png">

It does not match the Chrome dark theme.

<img width="1678" alt="Screen Shot 2019-11-01 at 12 39 27" src="https://user-images.githubusercontent.com/11660168/68002664-e0ed6080-fca4-11e9-8e96-d2e5d5aaffaf.png">

**Comment by Leowang628** [comment]
I also found this problem because the value of the sepia filter is too high

**Comment by hologerry** [comment]
And the auto mode is NOT fixed.
<img width="654" alt="Screen Shot 2019-11-01 at 13 42 01" src="https://user-images.githubusercontent.com/11660168/68004708-80aeec80-fcad-11e9-8b84-14bc0d2e9c87.png">

**Comment by alexanderby** [comment]
Sorry, by default it is set to 100% by mistake.

Please go to Settings -> Theme -> Scroll down -> Reduce Sepia.

**Comment by hologerry** [comment]
Thanks a lot, I have reduced the Sepia.
How about the auto mode?

**Comment by alexanderby** [comment]
@hologerry Regarding the Catalina Auto mode, maybe you have to reload tab in your case. Also I've seen an error in the internet about the macOS bug, that if you open System Preferences and choose "Dark" and then switch to "Auto" macOS will provide a wrong theme value and the extension will not be able to determine what is the actual theme. So maybe try selecting "Light" and then "Auto" in System preferences.

**Comment by hologerry** [comment]
Fixed!

**Comment by SimonAB** [comment]
Auto mode not fixed yet in Safari (Catalina): no transition to Catalina's 'Auto' appearance setting, whether from Light or from Dark, is picked up. (Other browsers work as expected, so this seems to be Safari and macOS 15.1-specific...).
