### ISSUE TITLE
Dark Reader doesn’t work without CORS

### ISSUE THREAD

**Issue by jiaweihli** [darkreader/darkreader#1802]
As title.  When the browser doesn’t set an ‘Origin’ header on the request for the stylesheet, the response fails the same origin policy and blocks dark reader from stylesheets.  Repros in Chrome.

**Comment by Gusted** [comment]
Example link?

**Comment by jiaweihli** [comment]
I don't have a public link I can share, but I can try to put together a small repro in a repo.

**Comment by Gusted** [comment]
Sure thing

**Comment by Gusted** [comment]
Should be fixed.

**Comment by domvo** [comment]
For me, it still doesn't work. I'm talking about the "standalone" version of dark reader. With some pages I get this cors error. In my case I want a generic dark reader script to be injected into arbitrary websites, so the admins of the websites have an easy way to offer this functionality. Is there something I can do about it? Thanks for the great work btw!

**Comment by Gusted** [comment]
Do you have any errors that were occurred in console when it happend, that you could provide.

**Comment by domvo** [comment]
Sure, here is an example error:
`Error: Embedded Dark Reader cannot access a cross-origin resource https://fonts.googleapis.com/css?family=Lato:300,400,900 Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works.`

Currently I'm in tryout phase, so this is what I'm doing to simulate the script injection:

```javascript
const newScript = document.createElement('script');
newScript.src = "https://cdn.jsdelivr.net/npm/darkreader@4.9.16/darkreader.min.js";
document.body.appendChild(newScript);
```
then
```javascript
Darkreader.enable() // potentially with some settings, this is just for demo purposes
```

**Comment by Gusted** [comment]
Have this code before enable
```Typescript
DarkReader.setFetchMethod(window.fetch)
```

**Comment by Gusted** [comment]
See https://darkreader.org/blog/v4-9-16/
it should contain some info to get the generated theme CSS

**Comment by domvo** [comment]
I tried this before, but only after doing `Darkreader.enable()` already. Apparently the setFetchMethod has no effect when Darkreader was already initialized. Thanks! Also for the link. And for the quick support! Keep up the good work.

**Comment by Gusted** [comment]
No problem! Have a nice day.

**Comment by domvo** [comment]
I actually have a follow-up question. Are there any known technical reasons why the standalone version does not work as well as the extension? I'm trying it with some websites and the extensions is much more reliable (i.e. darkens sites while standalone only darkens certain areas of the site or nothing).

**Comment by Gusted** [comment]
Hmm, make sure you have the latest version of the API 4.9.16. It should be as same of the extension, ONLY Iframe is not working and can't be fixed either due we just can't inject a cached script into it(etc the current source so it will not heavy on network). Instead it should be manually inserted into the Iframe and trough some tricky javascript you should enable it into Iframe's.

**Comment by domvo** [comment]
Assuming that the CDN version is in fact up to date (as stated in the url), I'm using the latest version. Also there are several sites, none of which are using an iframe, that do not work properly compared to the extension. Is there a way to contact you outside GH issues? Don't want to clutter this with offtopic questions. Thanks!

**Comment by Gusted** [comment]
`williamzijl7@hotmail.com`

Also
https://cdn.jsdelivr.net/npm/darkreader@latest/darkreader.min.js
https://unpkg.com/darkreader@latest/darkreader.js

Should be used to this kind of URL's to get the latest version.
also it's 1am so don't expect a response soon :P

Regards,
Gusted

**Comment by jiaweihli** [comment]
Did you 2 get this sorted out?  I'm in the process of updating to 4.9.16 and trying out the fix @Gusted suggested, crossing my fingers.

**Comment by jiaweihli** [comment]
The fix worked for me!  Thanks @Gusted!

**Comment by jiaweihli** [comment]
@Gusted 
On 4.9.16 I'm seeing rendering issues in Chrome again :|  But not Firefox or Safari.
Planning on bumping to 4.9.21, will update again later.

**Comment by Gusted** [comment]
> @Gusted
> On 4.9.16 I'm seeing rendering issues in Chrome again :| But not Firefox or Safari.
> Planning on bumping to 4.9.21, will update again later.

Hmm, could you open a seperate issue for that?

**Comment by rafaelmaeuer** [comment]
> Have this code before enable
> 
> ```ts
> DarkReader.setFetchMethod(window.fetch)
> ```

This solution is only partly working for me: I am building a flutter webview app for stackoverflow using [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) and I want to inject some dark styles with darkreader. Without `window.fetch` I get CORS-errors for all loaded css files:

```
flutter: darkreader loaded and ready to be used!
flutter: enable darkreader!
flutter: {message: Error: Embedded Dark Reader cannot access a cross-origin resource https://cdn.sstatic.net/Shared/stacks.css?v=616da833cd32 Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works., messageLevel: 3}
flutter: {message: Error: Embedded Dark Reader cannot access a cross-origin resource https://cdn.sstatic.net/Sites/stackoverflow/primary.css?v=a23a5ff87c8f Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works., messageLevel: 3}
flutter: {message: Error: Embedded Dark Reader cannot access a cross-origin resource https://cdn.sstatic.net/Shared/Product/product.css?v=8389559b0d89 Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works., messageLevel: 3}
flutter: {message: Error: Embedded Dark Reader cannot access a cross-origin resource https://cdn.sstatic.net/Shared/Channels/channels.css?v=89163e79f6d2 Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works., messageLevel: 3}
```

After setting `DarkReader.setFetchMethod(window.fetch)` some css-file loads, which causes visible changes in UI, but some css-files doesn't and the following error occurs twice:

```
flutter: {message: TypeError: Origin https://stackoverflow.com is not allowed by Access-Control-Allow-Origin., messageLevel: 3}
```

I already tried to set Content-Origin-Headers at all possible places and set values in flutters [CrossOrigin class](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/CrossOrigin-class.html) but nothing helps. Is this problem related to darkreader or flutter? I can't figure out how to get it fully working.

I also tried loading the darkreader-css generated from a browser. It works fine on e.g. pages like `deepl.com` but on StackOverflow only background colors are updated. I'm out of ideas now...

**Comment by Gusted** [comment]
That happens because the server itself is sending this `Access-Control-Allow-Origin` header, which doesn't match with stackoverflow.com I'm not sure which CSS it is as the error doesn't describe it. 

It's a bit out of our scope to help with this problem, as this is about how Browsers and CORS works - if you by any chance can get to call flutter code that will make the request that would be the best to avoid this CORS hell at all cost.

**Comment by rafaelmaeuer** [comment]
Hey and thanks a lot for your answer!!! I think the problematic css files are 

- https://cdn.sstatic.net/Sites/stackoverflow/primary.css
- https://cdn.sstatic.net/Sites/stackoverflow/secondary.css

as they both lack the `access-control-allow-origin: *` response header.

Could you please specify your meaning of `call flutter code that will make the request`?
Which request do you mean? Loading the css files?

**Comment by Gusted** [comment]
The current request will go trough the inbrowser and will have always such error(you cannot disable this). However if you can set the function of `setFetchMethod` to somehow call code from flutter itself to make the request you can bypass such issue. But I'm not a flutter/dart developer so I can be talking nonsense right now if that is possible.

**Comment by rafaelmaeuer** [comment]
Or let me ask some other question: why is loading of theses css files from the browser extension working and not in standalone js-mode?

**Comment by rafaelmaeuer** [comment]
Ok I think thats not possible, as the js-code injected to the webview can only be string: `It accepts a String as source code to be evaluated by the WebView` (https://inappwebview.dev/docs/javascript/injection). Too bad... what do you think about using an iFrame: https://github.com/darkreader/darkreader/issues/17?

**Comment by Gusted** [comment]
>  Too bad... what do you think about using an iFrame: #17?

#5085 IFrames are way way way harder if you want to go down that path, I had to modify an existing library to get around browser restrictions, see https://github.com/Gusted/cors-anywhere-iframe and https://github.com/Gusted/darkreader-web and even that have their limitations with cookies etc.

**Comment by rafaelmaeuer** [comment]
Thanks again for sharing this, I already though about some web-proxy solution that you have already built. Sadly StackOverflow isn't working there as expected, so the same problem seem to exists... 

Another sad thing is that StackOverflow has a native Darkmode built-in, but only on desktop, mobile versions are not respected and will not be supported: https://meta.stackexchange.com/a/366579

**Comment by Gusted** [comment]
>  Sadly StackOverflow isn't working there as expected, so the same problem seem to exists...

StackOverflow is one of the many sites that will need manually javascript patching, they are probably changing their top level source to the incorrect one, because they are being loaded from a url that isn't https://stackoverflow.com
