### ISSUE TITLE
extension creates 404 requests for images in css files with relative path

### ISSUE THREAD

**Issue by Bhoft** [darkreader/darkreader#1933]
This extension creates a lot of 404 requests on web servers which uses background-images in CSS files with an relative path.

e.g. i have following files:
`/test.html`
`/sub/test.html`
`/css/style.css`
`/css/images/background.png`

Content of /test.html  (for the test.html in sub directory href="../css/style.css"

    <!DOCTYPE html>
    <html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <title>test in root</title>
    </head>
    <body>
    <div class="my-class">
        this should have a background
    </div>
    </body>
    </html>

content of /css/style.css

    .my-class {
        height:500px;
        width: 500px;
        display: block;
        background: url("images/background.png") repeat scroll 0 0 green;
    }

e.g. if i open`/test.html`

**without dark reader enabled:**
![image](https://user-images.githubusercontent.com/1777147/73173893-b9246200-4106-11ea-9190-a8841e454d01.png)

**with dark reader enabled:**
![image](https://user-images.githubusercontent.com/1777147/73173865-a6aa2880-4106-11ea-91b5-9db7169cfae5.png)

the background image is requested 3 times!
http://localhost/test/image-test/css/images/background.png (correct path from the html code)
http://localhost/test/image-test/css/images/background.png (by the index.js code from the extension)
http://localhost/test/image-test/images/background.png  => 404 html error

> Relative URLs are allowed, and are relative to the URL of the stylesheet (not to the URL of the web page).

[CSS Url Syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/url#Syntax)

Same issue of course also for html requests which are located in sub directories e.g. `/sub/test.html`.

**Comment by matthijskooijman** [comment]
I'm seeing exactly the same issue when using the Django default admin interface. I can't share a URL, since it's password-protected, but it looks like exactly the problem @Bhoft has reported: The relative URL in a CSS file is resolved relative to the main HTML file instead of to the CSS file.

**Comment by Gusted** [comment]
#3055

**Comment by mppfiles** [comment]
I'm still experiencing this bug in version 4.9.16.
I'm using FF 79, but confirmed in latest Chrome and Opera.

Here I have setup a [simple site](https://mppfiles.github.io/test-static-page/) to test the issue.
If you change the theme mode from dynamic to something else, the issue dissapears.

**Comment by mppfiles** [comment]
@Gusted can you please confirm the issue with the test site I provided above? :pray:

**Comment by Gusted** [comment]
![](https://i.imgur.com/ZQv6L43.png) The traceback of the invalid image isn't to dark reader related however if you disable darkreader you don't get it. Firefox is also indicating from html trace. So unsure what the problem is. I only know the background is now their but are still getting 404 requests to the invalid URL somehow

**Comment by Gusted** [comment]
![](https://i.imgur.com/edwHl0m.gif)
https://github.com/darkreader/darkreader/blob/master/src/utils/network.ts#L34
Somehow .blob() is causing this error...

**Comment by Gusted** [comment]
[case.zip](https://github.com/darkreader/darkreader/files/5278502/case.zip)

**Comment by aaronamm** [comment]
This error happens to me as well.

Here is part of my CSS that has relative image URL.
```
header.masthead {
    padding-top: 10rem;
    padding-bottom: calc(10rem - 4.5rem);
    background: linear-gradient(to bottom, rgba(92, 77, 66, 0.8) 0%, rgba(92, 77, 66, 0.8) 100%), url(../img/bg-masthead.jpg);
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: scroll;
    background-size: cover;
}


```

There is a request to /img/bg-masthead.jpg which does not exist.
Here is the error when I have dark reader. 
![image](https://user-images.githubusercontent.com/2938310/104819061-bbbf2080-585d-11eb-9738-7302f8de1de1.png)

After I removed Dark reader, the error has gone.
![image](https://user-images.githubusercontent.com/2938310/104819115-02ad1600-585e-11eb-90f6-ea54fd859afe.png)

**Comment by tidalvirus** [comment]
I experienced this with the absolute basic files in the tutorials for django - https://docs.djangoproject.com/en/4.0/intro/tutorial06/ - on the off chance it helps. Had me scratching my head for some time before I realised it might be plugins, disabling darkreader fixed it for me.
I had the site hosted at localhost, so I can't share the site as such.

**Comment by bartektrybala** [comment]
In Dark Reader settings you can choose theme generation mode other than Dynamic but every other isn't cool. You can also write your custom theme mode with click on Static theme generation mode.

**Comment by stefan6419846** [comment]
I just stumbled upon the same issue after seeing seemingly random 404 entries in my log file when using `background-image: url('../../images/image.png')` in my CSS files.

**Comment by dub357** [comment]
yea this is still a problem. DarkReader seems to not work with respect to relative paths in the CSS.  I'm not sure why this plugin needs to do anything w/ images in the first place, but when its doing its thing, it triggers requests for the images referenced in the CSS by using the browser URL instead of the actual URL to the CSS resource as your browser would.
So if I'm on page:
http://www.someserver.com/module/page.html

and that page references a CSS file like:
`<link rel="stylesheet" media="all" href="/assets/site.css" />`

and that CSS file has a declaration like:
```
.something {
  background: url('some-image.jpg');
}
```
when DarkReader does its thing, it triggers a request to some-image.jpg at location:
http://www.someserver.com/module/some-image.jpg
which is incorrect as resolving the relative path in the CSS should be based on the path to the CSS file itself and not the path to the HTML page.
DarkReader should trigger a request to fetch the image with this path:
http://www.someserver.com/assets/some-image.jpg

**Comment by Himura2la** [comment]
I also experience this problem with relative paths. The CSS is like `background-image:url(../../imgs/Arrows/arrow-menu-normal.svg);`, but Dark Reader tries to make a request to `url(../../../imgs/Arrows/arrow-menu-normal.svg);`.

**Comment by yevgeni-accessibe** [comment]
the cause for this issue is when modifies the stylesheet rules, it still add the relative urls. instead, replace the rules with the absolute urls (with `rule.style.setProperty`) and only then analyze it.

managed to come up with a "hacky" solution using patch-package.
in `modify-css.ts`:
added this to the start of `shouldIgnoreImage` to prevent from analyzing images that might not be relevant:
```
 if (selectorText && !document.querySelector(selectorText)) {
        return true;
    }
```

and added this before calling `getBgImageModifier`:
```
if (value.startsWith('url(".')) {
            const urls = getMatches(cssURLRegex, value);
            let newURL = '';
            for (let i = 0; i < urls.length; i++) {
                const url = urls[i];
                const {parentStyleSheet} = rule;
                const baseURL = (parentStyleSheet && parentStyleSheet.href) ?
                    getCSSBaseBath(parentStyleSheet.href) :
                parentStyleSheet!.ownerNode?.baseURI || location.origin;
                newURL += `url("${getAbsoluteURL(baseURL, getCSSURLValue(url))}")${urls[i + 1] ? ', ' : ''}`;
            }
            value = newURL;
            rule.style.setProperty(property, newURL, rule.style.getPropertyPriority(property));
        }
```

**Comment by dickinr** [comment]
This really needs to be fixed. Users using this extension are causing my application to get needless 404 requests.

**Comment by alexanderby** [comment]
@dickinr Could you please share an example where it happens?

**Comment by alexanderby** [comment]
Thank you, I will try to reproduce the path problem.

**Comment by alexanderby** [comment]
Should be fixed already by https://github.com/darkreader/darkreader/commit/4c4377383e78d0526f0d978e4e15e0f05a11d012

**Comment by PatrykStefaniak** [comment]
We're still facing this issue in [our application](https://voipstudio.com/app/#dashboard,login). Seems like all of the relative paths added to the css files by our framework are being requested with full url and causing lots of 404 errors.
