### ISSUE TITLE
[Broken Website] Background not turning dark but other elements such as text are.

### ISSUE THREAD

**Issue by VivekSharma1897** [darkreader/darkreader#2512]
**Website**
https://myanimelist.net/

**Expected behavior**
Background should be dark.

**Actual behavior**
Background is still white but the text color inverts and also turns into white.
It is working as expected if I uncheck and check website in the dark reader extension.

**System info:**
 - OS: Windows
 - Browser: Chrome
 - Darkreader Version : 4.9.8

**Comment by sprinkledcheese** [comment]
Can't reproduce in 4.9.9.

**Comment by Gusted** [comment]
This has been fixed #2065

**Comment by leosolid** [comment]
![Screenshot 2021-05-21 123842](https://user-images.githubusercontent.com/13348080/119189975-96236d00-ba31-11eb-8073-3f418719c7fa.png)

still happening for me randomly on 4.9.32, but i dont know repro steps

**Comment by Kurogal** [comment]
> ![Screenshot 2021-05-21 123842](https://user-images.githubusercontent.com/13348080/119189975-96236d00-ba31-11eb-8073-3f418719c7fa.png)
> 
> still happening for me randomly on 4.9.32, but i dont know repro steps

For me it happens consistently when I open a link in a new background tab, and then let it fully load before swapping to it.

Minus user's lists both new and old design, I can do it with pretty much any other link by using middle mouse button in chrome to do it, but it's easy to get a bunch of them by going to an person's page and then just middle mouse buttoning all of their stuff and doing something else for a bit while all the tabs load in the background.

https://myanimelist.net/people/10308/Gen_Urobuchi

It also works from following an external link to MAL for me, like middle mouse buttoning the link in the OP.

The reason it doesn't happen with user lists is likely because both new and old designs are defined by custom user set CSS that doesn't seem to care, even if they haven't touched it and it's just the default new design white, it turns black as normal even if I let it load first in a background tab.

I can also do it inconsistently by clicking on a link and then quickly swapping tabs and waiting for it to fully load before swapping back, assuming again that it's not a user's anime/manga list.
And have had no luck with copying and pasting a link into my address bar and then swapping away so far.
