### ISSUE TITLE
[BUG] Dynamic filter totally broken

### ISSUE THREAD

**Issue by privacyguy123** [darkreader/darkreader#4204]
### **Describe the bug**

Screenshot says it all.

### **Screenshots**
![image](https://user-images.githubusercontent.com/50337995/99791266-4c5ad800-2b1d-11eb-812e-1b9e21536280.png)

### **System Information:**

- OS: Windows 10
- Browser: FireFox 83
- Dark Reader version: Latest

**Comment by privacyguy123** [comment]
Twitter also broken.

**Comment by Gusted** [comment]
>     * Dark Reader version: Latest

This doesn't provide any information.

Update to v4.9.24 as it contains a fix.

**Comment by privacyguy123** [comment]
I'm on 4.9.24 - still totally broken - don't think you should close tickets before they're resolved mate.

**Comment by Gusted** [comment]
> I'm on 4.9.24 - still totally broken - don't think you should close tickets before they're resolved mate.

They are resolved however you don't have the fix for this problem for some weird reason.

**Comment by privacyguy123** [comment]
> 
> 
> > I'm on 4.9.24 - still totally broken - don't think you should close tickets before they're resolved mate.
> 
> They are resolved however you don't have the fix for this problem for some weird reason.

I can confirm I've tried everything right down to a re-installation of FireFox and Dark Reader and I still see this bug. I can confirm I use 70% on Contrast also.

**Comment by Gusted** [comment]
> I can confirm I use 70% on Contrast also.

Reset it temporarily for github and poof the issue is resolved. We are using variables that are generated from user's selected dark background, however it currently don't take any Brightness/Contrast/Sepia/Gray scale in consideration and therefore don't match up with the 'fix' and still give you a broken github.com I've opened up a PR #4220 to fix this exact issue.

Regards,
Gusted

**Comment by privacyguy123** [comment]
Would Twitter somehow fall into this category too? After a page refresh I see this weirdness:

![image](https://user-images.githubusercontent.com/50337995/99905687-49e9b100-2cca-11eb-8813-2d7537183a80.png)

**Comment by Gusted** [comment]
> Would Twitter somehow fall into this category too? After a page refresh I see this weirdness:

Hmm also open up a new issue for this weird bug.

> Can you advise how to sideload an addon into FireFox 83?

`about:debugging#/runtime/this-firefox` -> Load temporary Add-on
