### ISSUE TITLE
[Broken Website] allegro.pl

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5632]
For some reason details tab about seller does not loading content when darkreader works. 
Fix for graphic `Smart!` does not work anymore too. 

Reproduce:
Open any offer site: (random here). Click on seller name link for details. 
https://allegro.pl/oferta/apple-watch-6-40mm-zloty-milanese-od-reki-fv23-9799539136

![20210424-1619294338-001](https://user-images.githubusercontent.com/9846948/115971388-78550c00-a548-11eb-83ea-78fe8f4a211b.png)

![20210424-1619294375-001](https://user-images.githubusercontent.com/9846948/115971387-7723df00-a548-11eb-96ce-29bf8ae6faee.png)

Console Chrome says
![20210424-1619294487-001](https://user-images.githubusercontent.com/9846948/115971413-a1759c80-a548-11eb-8076-e43e9bc9478b.png)

Without active dark reader error gone. 
![20210424-1619294551-001](https://user-images.githubusercontent.com/9846948/115971442-c702a600-a548-11eb-97b3-0774a9147822.png)

**Comment by TheLastGimbus** [comment]
Oh, so it was dark reader that was breaking it! I was really annoyed by this recently - also, their new "search multiple" function is broke, don't know if it's because of dark reader...

**Comment by FadeMind** [comment]
@TheLastGimbus co ciekawe to samo dzieje się przy użyciu USO > https://33kk.github.io/uso-archive/?search=allegro&sort=updated&style=200261

🤯

**Comment by Gusted** [comment]
So first, make sure you have Ublock Origin disabled as it seems like it's blocking certain network request related to seller info/search and then make sure to have the latest config as it was fixed a few days ago this issue.

**Comment by FadeMind** [comment]
With disabled Adguard is SAME. Not related with adblocking at all. @Gusted thats why I open this issue here.

**Comment by Gusted** [comment]
> Not related with adblocking at all.

I've mentioned that uBlock Origin enabled blocked some features(which it shouldn't btw) however upon disabling It was already fixed and that would need the latest config file. Because this change https://github.com/darkreader/darkreader/pull/5245 is in effect for the seller information and correctly make those white areas dark again.

**Comment by FadeMind** [comment]
@Gusted 
is not fixed. 
![20210426-1619422807-001](https://user-images.githubusercontent.com/9846948/116046545-7a67b980-a673-11eb-999d-2884c0b543d4.png)
![20210426-1619422759-001](https://user-images.githubusercontent.com/9846948/116046549-7b005000-a673-11eb-9c6f-6fe324c77d2b.png)
![20210426-1619422737-001](https://user-images.githubusercontent.com/9846948/116046551-7b98e680-a673-11eb-9db7-07b710dd1637.png)

**Comment by Gusted** [comment]
Cannot think of anything else, so it might be #5648

**Comment by FadeMind** [comment]
@Gusted progress:
![20210426-1619426705-001](https://user-images.githubusercontent.com/9846948/116055311-dc78ec80-a67c-11eb-9e91-dea758131f0e.png)
![20210426-1619426691-001](https://user-images.githubusercontent.com/9846948/116055316-ddaa1980-a67c-11eb-86c8-59b84538abf5.png)
Last thing:
`Smart!` logo is not properly inverted. 

![20210426-1619426948-001](https://user-images.githubusercontent.com/9846948/116055492-0df1b800-a67d-11eb-8350-fb066c8f90d2.png)
![20210426-1619426936-001](https://user-images.githubusercontent.com/9846948/116055496-0e8a4e80-a67d-11eb-9e6d-aeaf982d6275.png)
```
INVERT
i[title="Smart!"]
```
did not work anymore. 

I have latest build darkreader (nodejs). 
Chrome.

**Comment by Gusted** [comment]
🤷🏽‍♀️ Not sure where I can find those sections that your showing.

**Comment by FadeMind** [comment]
![20210426-1619428292-001](https://user-images.githubusercontent.com/9846948/116058576-45ae2f00-a680-11eb-9758-8d49cb1a2d1e.png)
![20210426-1619428170-001](https://user-images.githubusercontent.com/9846948/116058583-4646c580-a680-11eb-8665-ddc0e3120f1f.png)

Selector
```
_._12h65 {
    background-image: url("blob:https://allegro.pl/ecb89602-be7a-4cd7-9119-3c6f6ad5962d");
}
```
```
._12h65 {
    background-image: url(https://assets.allegrostatic.com/metrum/icon/logotype-783106c3de.svg);
}
```

**Comment by Gusted** [comment]
#5650

**Comment by FadeMind** [comment]
@Gusted thanks

![20210426-1619440583-001](https://user-images.githubusercontent.com/9846948/116083371-d3981300-a69c-11eb-90db-3690cbb6fa64.png)
