### ISSUE TITLE
[Broken Website] Mozilla.org

### ISSUE THREAD

**Issue by DJ-Katalina** [darkreader/darkreader#6213]
# Broken Website
## Website
https://www.mozilla.org/en-US/firefox/new/

## How to Reproduce

  Visit Site

## Expected behavior
The images are displayed correctly and are readable / viewable.

## Actual behavior
The images are not displayed correctly and are not readable / viewable.

## Screenshots
Issues with site are highlighted in red:

![mozilla org](https://user-images.githubusercontent.com/87130982/124930788-3e33cc00-dfc7-11eb-9498-4a8a985e405a.png)

## System Information

- OS: Windows 10 21H1 (19043.1083)
- Browser: Firefox Nightly 91.0a1 (20210708091856)
- Dark Reader Version: 4.9.34

## Additional context
I did a search for previous issues and came across this one: #5957; however, the site is still not being displayed correctly.

I wasn't sure whether to open a new issue or just append a comment to the old issue. (I am new to the whole GitHub Report an Issue process).

**Comment by Gusted** [comment]
Hmm, that issue should be fixed entirety. Also this doesn't make sense because of the images is loaded and the other isn't. But it's either both are unaffected or both are affected.

**Comment by Gusted** [comment]
Does this still happen on a new profile? `about:profiles`

**Comment by DJ-Katalina** [comment]
Hi @Gusted!

Yes, this issue still happens on a brand new profile.

I just created a new profile and added Dark Reader from Firefox's AMO. I visited the site and it still happens. No other changes made to new profile.
