### ISSUE TITLE
[Broken Website] Classroom.Google.Com has Wierd Icons while Viewing Files

### ISSUE THREAD

**Issue by RuthlessRuler** [darkreader/darkreader#6389]
# Broken Website Report

## Website Address
classroom.google.com

## Steps To Reproduce

- Go to Above Website
- Open any class
- Click on the file attached on any assignment/post 

## Expected Behavior

- The UI Elements/Icons are properly displayed (Refer SS)

## Actual Behavior

- Weird Glitch which changes the icon itself  & glitches it out. Plus some inversion not taking place correctly. (refer SS)

## Screenshots

Without DarkReader:
![image](https://user-images.githubusercontent.com/20885012/127651973-793f9805-f702-4bea-a41b-6fe58f03eb7a.png)
![image](https://user-images.githubusercontent.com/20885012/127652046-79086027-cfbb-4578-92f2-0664500a0d59.png)

After DarkReader;
![image](https://user-images.githubusercontent.com/20885012/127652207-f17d2b2f-2368-4c34-b293-29d2fdea374d.png)
![image](https://user-images.githubusercontent.com/20885012/127652260-19e9df4f-4d31-42e5-a2fc-a8020fc3b703.png)

## System Information

- OS: Windows & Linux
- Browser: Firefox 90.0.2
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
This is already fixed in the next release of darkreader. See https://github.com/darkreader/darkreader#site-fixes how to get fixes before next release.

**Comment by RuthlessRuler** [comment]
Hey @Gusted . Well its still busted and not really fixed. I enabled the preview version (ie. 4.9.35 Preview 5) & enabled auto update of definitions but the icons werent still showing up correct. 
Also just to make myself clear, this occurs when i click on a attached document on Google Classroom Website (classroom.google.com). 

Here are some SS, maybe to further elaborate in current situation. 
![SS1](https://user-images.githubusercontent.com/20885012/134572647-122e0788-16c6-4fd6-af18-97f60d261474.png)
(With Dark Reader ON )

![SS2](https://user-images.githubusercontent.com/20885012/134572655-a2e1d541-8371-437a-9dda-d2c89078f73c.png)
(With Dark Reader Off)

![SS3](https://user-images.githubusercontent.com/20885012/134572656-00c8aefe-457a-463b-aa35-2bffef1bd3c3.png)
(With Dark Reader ON)

![SS4](https://user-images.githubusercontent.com/20885012/134572658-ac57e1ab-7cc3-43f9-8f63-cf75935992a8.png)
(With Dark Reader Off)

**Comment by Gusted** [comment]
Please first update to v4.9.36 and then go to the popup, dev tools button, click on "reset" to force the newest fixes.

**Comment by RuthlessRuler** [comment]
> Please first update to v4.9.36 and then go to the popup, dev tools button, click on "reset" to force the newest fixes.

Okay I did that, weirdly enough it fixed it for me. Thanks alot. 

Also, a report that it is broken for drive.google.com/file/d/* even after following the above steps
![image](https://user-images.githubusercontent.com/20885012/134701991-cf439da7-0f5a-4562-a189-a06af6d96c5f.png)
![image](https://user-images.githubusercontent.com/20885012/134702150-8cb47a23-626d-4d56-9504-15a8c3325b5b.png)

**Comment by Gusted** [comment]
We've a outstanding issue about this specific issue which was for now always solved with CSS which had to be updated once in a while. But I've finally got the root issue and fixed it for a eternity #6895

**Comment by RuthlessRuler** [comment]
Thanks a lot for fixing this issue too.
