### ISSUE TITLE
[Broken Website] pcgarage.ro

### ISSUE THREAD

**Issue by Fanatiikon** [darkreader/darkreader#8274]
# Broken Website Report

## Website Address
 https://www.pcgarage.ro/placi-video/
## Steps To Reproduce

1. Click the provided link
2. Observe the filters remain white

## Problematic Observation
 Whenever you select a one of the top options(which are electronic device sub sections) the filters appear on the left and they are in white rectangles.

## Screenshots

![image](https://user-images.githubusercontent.com/76494177/155409402-5bcbca24-25cd-4fc2-880f-a1290fde4ce1.png)

## System Information

- OS:  Windows
- Browser:  Chrome 98.0.4758.102
- Dark Reader Version:  4.9.45

## Additional Context
 The website used to work correctly until they changed it a bit. 
Won't let me actually attach a link to it for some reason it shows up in text whenever i try to attach it to the name up top.

**Comment by Gusted** [comment]
Hi @Fanatiikon!

I'm not able to reproduce this issue, does this issue persist between restarts?

Regards,
Gusted

**Comment by Fanatiikon** [comment]
It does persist. It is permanently like this. I've added a screenshot of it also looking the same in incognito with only ublock origin and Dark reader enabled.
![image](https://user-images.githubusercontent.com/76494177/155709248-24e488ec-82ac-4715-a968-58271af51c73.png)

**Comment by Fanatiikon** [comment]
One more thing clicking straight on one of the top options will result in it not reproducing as they use a different layout for the categories.
![image](https://user-images.githubusercontent.com/76494177/155709410-8cde8bb9-6061-4d07-adad-d1fb311b97cf.png)

It reproduces for example when clicking Componente-> Placi Video
![image](https://user-images.githubusercontent.com/76494177/155709528-ce076d4b-15b8-49e2-bc12-75e89e7dd53a.png)

**Comment by Gusted** [comment]
Seems like it's fixed with: https://github.com/darkreader/darkreader/commit/a61b80fb4f690d05c7854364a458a38d6c552e68 Could you make sure you're on the latest dark reader version?

**Comment by Fanatiikon** [comment]
I am on 4.9.45 and https://github.com/darkreader/darkreader/issues/8157 is not fixed for me either i've attached screenshots.
![image](https://user-images.githubusercontent.com/76494177/155888208-47806e36-c8de-491e-ad2d-f6ab7dcee658.png)
![image](https://user-images.githubusercontent.com/76494177/155888239-0da986f3-b6ac-43eb-bad7-0a2852313910.png)
![image](https://user-images.githubusercontent.com/76494177/155888246-6f8c8f42-9c0c-4190-a0a0-b6d2666e8104.png)

**Comment by Fanatiikon** [comment]
I've checked on Firefox to make sure that the fix wasn't just forgotten on Chrome, for one reason or another, and i'm getting mixed results.
PCGarage is fixed on Firefox but the imdb page is still broken.
![image](https://user-images.githubusercontent.com/76494177/155888418-d1d614d3-f343-41b0-a62d-896f6f3db522.png)
![image](https://user-images.githubusercontent.com/76494177/155888422-7037e30c-283a-4ab7-8c4f-6b02d4caa7df.png)
![image](https://user-images.githubusercontent.com/76494177/155888427-117ec388-0e83-4c83-901d-6a65dbc98875.png)

**Comment by Gusted** [comment]
My fault, it hasn't been included in 4.9.45.

**Comment by Fanatiikon** [comment]
Both #8157 and this are fixed for me in 4.9.47.
